name: deploy-hackernews-app-heroku                       # 1

on:
  push:
    branches:                                            # 2
      - master
      - main

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                        # 3
      - run: npm ci                                      # 4
      - name: Run production migration                   
        run: npm run migrate:deploy                      # 5     
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - uses: akhileshns/heroku-deploy@v3.12.12          # 6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}